name: Build Executable

on:
  push:
    branches:
      - main  # Change to your default branch if different
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller Library.spec  # Use the .spec file to build the executable
          cd dist && mv Library Library.exe && cd ..
      - name: Commit executable
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add .
          git lfs track "*.exe"
          git commit -m "Library.exe-v1.21"
          git push origin main  # Push back to the main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
